function onCreate()
    addHaxeLibrary('Song')
    addHaxeLibrary('SwagSong', 'Song')
    addHaxeLibrary('Section')
    addHaxeLibrary('SwagSection', 'Section')
    addHaxeLibrary('Std')
    addHaxeLibrary('Math')
    addHaxeLibrary('FlxMath', 'flixel.math')
    addHaxeLibrary("FlxG", 'flixel')
    addHaxeLibrary("FlxCamera", 'flixel')
    addHaxeLibrary("ShaderFilter", "openfl.filters")
    addHaxeLibrary('FlxTimer', 'flixel.util')
    addHaxeLibrary('Type')
    addHaxeLibrary("FlxFlicker", 'flixel.effects')
	addHaxeLibrary("FlxEase", 'flixel.tweens')
	addHaxeLibrary("FlxTween", 'flixel.tweens')
    addHaxeLibrary("FlxColor", 'flixel.util')
    if stringStartsWith(version, '0.6') then
        addHaxeLibrary("Rating", 'Conductor')
		addHaxeLibrary("Highscore")
		addHaxeLibrary("CoolUtil")
        addHaxeLibrary("Alphabet")
        addHaxeLibrary('StrumNote')
        addHaxeLibrary("Paths")
        addHaxeLibrary("Note")
        addHaxeLibrary('Character')
		addHaxeLibrary('HealthIcon')
    else
        addHaxeLibrary("Rating", 'backend.Conductor')
		addHaxeLibrary("Highscore", 'backend')
		addHaxeLibrary("CoolUtil", 'backend')
        addHaxeLibrary("Alphabet", "objects")
        addHaxeLibrary('StrumNote', 'objects')
        addHaxeLibrary("Paths", "backend")
        addHaxeLibrary("Note", 'objects')
        addHaxeLibrary('Character', 'objects')
		addHaxeLibrary('HealthIcon', 'objects')
    end
    addHaxeLibrary("PauseSubState")
    addHaxeLibrary("StringTools")
	addHaxeLibrary("FunkinLua")
    addHaxeLibrary("FlxTrail", 'flixel.addons.effects')
    addHaxeLibrary("FlxTrailArea", 'flixel.addons.effects')
end