function onCreate()
    makeLuaSprite('schoolSTATIC', 'main/funnyAnimal/schoolBG', -1670, -600)
    scaleObject('schoolSTATIC', 1.8, 1.8)
    updateHitbox('schoolSTATIC')
    addLuaSprite('schoolSTATIC', false)

    makeAnimatedLuaSprite('RUNBITCHSTATIC', 'main/funnyAnimal/runningThroughTheHalls', -240, 100)
    addAnimationByPrefix('RUNBITCHSTATIC', 'run', 'Symbol 2', 24, false)
    playAnim('RUNBITCHSTATIC', 'run', true)
    setProperty('RUNBITCHSTATIC.visible', false)
    scaleObject('RUNBITCHSTATIC', 1.8, 1.8)
    updateHitbox('RUNBITCHSTATIC')
    addLuaSprite('RUNBITCHSTATIC', false)

    makeAnimatedLuaSprite('RUNBITCH', 'main/funnyAnimal/runningThroughTheHalls', -240, 100)
    addAnimationByPrefix('RUNBITCH', 'run', 'Symbol 2', 24, true)
    playAnim('RUNBITCH', 'run', true)
    setProperty('RUNBITCH.visible', false)
    scaleObject('RUNBITCH', 1.8, 1.8)
    updateHitbox('RUNBITCH')
    addLuaSprite('RUNBITCH', false)

    makeAnimatedLuaSprite('BFLEGS2', 'main/funnyAnimal/legs_working', -500, 700)
    addAnimationByPrefix('BFLEGS2', 'e', 'legs0', 24, true)
    playAnim('BFLEGS2', 'e', true)
    setProperty('BFLEGS2.visible', false)
    setProperty('BFLEGS2.flipX', true)
    scaleObject('BFLEGS2', 0.7, 0.7)
    updateHitbox('BFLEGS2')
    addLuaSprite('BFLEGS2', false)

    makeLuaSprite('blackScreenBG', '', 0, 0)
    makeGraphic('blackScreenBG', '1280', '720', '000000')
    setProperty('blackScreenBG.visible', false)
    scaleObject('blackScreenBG', 10, 10)
    screenCenter('blackScreenBG', 'x')
    screenCenter('blackScreenBG', 'y')
    updateHitbox('blackScreenBG')
    addLuaSprite('blackScreenBG', false)

    makeLuaSprite('blackScreen', '', 0, 0)
    makeGraphic('blackScreen', '1280', '720', '000000')
    setObjectCamera('blackScreen', 'camhud')
    setProperty('blackScreen.visible', false)
    scaleObject('blackScreen', 5, 5)
    updateHitbox('blackScreen')
    addLuaSprite('blackScreen', true)

    makeLuaSprite('Jail', 'main/funnyAnimal/jailCell', 0, 0)
    setProperty('Jail.visible', false)
    scaleObject('Jail', 1.8, 1.8)
    screenCenter('Jail', 'x')
    screenCenter('Jail', 'y')
    setProperty("Jail.y", getProperty("Jail.y") + 75)
    updateHitbox('Jail')
    addLuaSprite('Jail', false)

    makeLuaSprite('IPADBG', 'main/funnyAnimal/futurePadBG', screenWidth -1800, screenHeight -1150)
    setProperty('IPADBG.visible', false)
    scaleObject('IPADBG', 2, 2)
    updateHitbox('IPADBG')
    if not lowQuality then
        addLuaSprite('IPADBG', false)
    end

    makeLuaSprite('IPAD', 'main/funnyAnimal/futurePad', screenWidth -1800, screenHeight -1150)
    setProperty('IPAD.visible', false)
    scaleObject('IPAD', 2, 2)
    updateHitbox('IPAD')
    addLuaSprite('IPAD', true)
end